### PR TITLE
Copyedited the document

### PR DESCRIPTION
**Pull request by Sayanta66**
## Read then delete

- Make sure to use a concise title for the pull-request.
- Use #patch, #minor #majora or #none in the pull-request title to bump the corresponding version. Otherwise, the patch version
  will be bumped. [More details](https://github.com/marketplace/actions/github-tag-bump)

# TL;DR
_Please replace this text with a description of what this PR accomplishes._

## Type
- [ ] Bug Fix
- [ ] Feature
- [ ] Plugin
- [x] Docs

## Are all requirements met?

- [ ] Code completed
- [ ] Smoke tested
- [ ] Unit tests added
- [ ] Code documentation added
- [ ] Any pending items have an associated Issue

## Complete description

I fixed the documentation with punctuation error and verbal errors.

## Tracking Issue
https://github.com/flyteorg/flyte/issues/<number>

## Follow-up issue
_NA_
OR
_https://github.com/flyteorg/flyte/issues/<number>_

### CODE REVIEW

**Comment by samhita-alla** [comment]
Hi, @Sayanta66! Is this a hacktoberfest-related PR?

**Comment by Sayanta66** [comment]
I have to work on all of the docs? Or just this doc?

**Comment by Sayanta66** [comment]
@samhita-alla Can I copy-edit on a doc by doc basis. Because that will be easy I guess? It will form a lot of PR but will break the work

**Comment by samhita-alla** [comment]
> I have to work on all of the docs? Or just this doc?

The whole `flytectl` docs, i.e., all pages under the flytectl repo. You can find all the pages here: https://docs.flyte.org/projects/flytectl/en/stable/. As mentioned in the issue, the docs should be very user-friendly—no typos, grammatical errors, etc. You can find the remaining requirements in the issue's comments.

**Comment by Sayanta66** [comment]
And you can merge this PR or atleast Review it because it has fixed some problems. I will do all the docs today.

**Comment by samhita-alla** [comment]
> And you can merge this PR or atleast Review it because it has fixed some problems. I will do all the docs today.

Please create a PR for all the changes at once. That would be helpful.

**Comment by Sayanta66** [comment]
Only issues will be merged or else it will not be merged, right?

**Comment by kumare3** [comment]
> Only issues will be merged or else it will not be merged, right?

No doc edits don't necessarily need an issue. Thank you for the help ❤️

**Comment by kumare3** [comment]
Also you have to sign off the commit as per linux foundation guidelines

**Comment by Sayanta66** [comment]
@kumare3 and @samhita-alla I opened another big PR so closing this. Can you please review it? So that I will be able to complete coyediting of the rest.

**Pull request closed without merging**
