### PR TITLE
Added a new flag for kustomize support

### PR DESCRIPTION
**Pull request by evalsocket**
# TL;DR
Docker change - https://github.com/flyteorg/flyte/pull/1224

- Added flag for kustomize support in `flytectl sandbox start` 

```bash
$ flytectl sandbox start --version=v0.15.0 --kustomize=kustomization.yaml
```

`kustomization.yaml` file
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - flyte_generated.yaml
  
images:
- name:
   registry: 
```

## Type
- [ ] Bug Fix
- [x] Feature
- [ ] Plugin

## Are all requirements met?

- [ ] Code completed
- [ ] Smoke tested
- [ ] Unit tests added
- [ ] Code documentation added
- [ ] Any pending items have an associated Issue

## Complete description
_How did you fix the bug, make the feature etc. Link to any design docs etc_

## Tracking Issue
https://github.com/flyteorg/flyte/issues/<number>

## Follow-up issue
_NA_
OR
_https://github.com/flyteorg/flyte/issues/<number>_

### CODE REVIEW

**Comment by wild-endeavor** [comment]
What does this do?  Does it override the existing yaml?  Or does it merge it?  Will it delete resources?

**Comment by evalsocket** [comment]
It will add user's kustomize file in a sandbox cluster. sandbox will build and then deploy the kustomize output

**Comment by wild-endeavor** [comment]
How does it interact with the existing sandbox yaml? Will it delete resources?

**Comment by evalsocket** [comment]
If you did not pass `--kustomize` flag then we will not build kustomize. If you provide the kustomize flag then it will build and then deploy the image.

This feature only available in flyte v0.16.0 and i merged on pr in flyte for supporting the kustomize in docker https://github.com/flyteorg/flyte/pull/1224

**Comment by evalsocket** [comment]
I am closing this. I will create a pr after helm changes are done in sandbox

**Pull request closed without merging**
