### PR TITLE
Added script for checking diff of generated code

### PR DESCRIPTION
**Pull request by evalsocket**
# TL;DR
- Added check for verify go-gen, it will fail if contributor forget to generate code

## Type
- [ ] Bug Fix
- [x] Feature
- [ ] Plugin

## Are all requirements met?

- [x] Code completed
- [x] Smoke tested
- [x] Unit tests added
- [x] Code documentation added
- [ ] Any pending items have an associated Issue

## Complete description
_How did you fix the bug, make the feature etc. Link to any design docs etc_

## Tracking Issue
https://github.com/flyteorg/flyte/issues/1872

## Follow-up issue
_NA_
OR
_https://github.com/flyteorg/flyte/issues/<number>_

### CODE REVIEW

**Comment by evalsocket** [comment]
@pmahindrakar-oss Any idea why workflow is failing https://github.com/flyteorg/flytectl/runs/4405899515?check_suite_focus=true

**Comment by pmahindrakar-oss** [comment]
```
time="2021-12-03T08:56:22Z" level=info msg="Finding all fields in [github.com/flyteorg/flytectl/cmd/config/subcommand/sandbox.sandbox.Config]"
time="2021-12-03T08:56:22Z" level=info msg="[source] is of a basic type with default value [*new(string)]."
time="2021-12-03T08:56:22Z" level=info msg="[version] is of a basic type with default value [*new(string)]."
time="2021-12-03T08:56:22Z" level=info msg="[image] is of a basic type with default value [*new(string)]."
Error: invalid type. it must be struct, received [int] for field [imagePullPolicy]
Usage:
  pflags MyStructName --package myproject/mypackage [flags]
[command]

Examples:

// go:generate pflags MyStruct
type MyStruct struct {
	BoolValue        bool              `json:"bl" pflag:"true"`
	NestedType       NestedType        `json:"nested"`
	IntArray         []int             `json:"ints" pflag:"[]int{12%2C1}"`
}
	

Available Commands:
              
  help        Help about any command

Flags:
      --bind-default-var     The generated PFlags Set will bind fields to the default variable.
      --default-var string   Points to a variable to use to load default configs. If specified & found, it'll be used instead of the values specified in the tag. (default "defaultConfig")
  -h, --help                 help for pflags
  -p, --package string       Determines the source/destination package. (default ".")

gs [command] --help" for more information about a command.

```
I believe this is already fixed in latest stdlib code by Haytham. Can you check if your branch is using latest stdlib

**Comment by evalsocket** [comment]
@pmahindrakar-oss it is fixed and we are also using correct branch, It's working in sandbox flags dir/Goland

**Comment by evalsocket** [comment]
@pmahindrakar-oss issue is wrong pflag binary in CI, You can review now, 

I also created a pr in boilerplate https://github.com/flyteorg/boilerplate/pull/47

**Review by pmahindrakar-oss — APPROVED** [review]

**Pull request merged**
