### PR TITLE
Fix docs for updating description using workflow-meta subcommand

### PR DESCRIPTION
**Pull request by goyalankit**
# TL;DR
The subcommand (`flytectl update workflow`) in docs doesn't exist and should be `workflow-meta` instead.

## Type
- [x] Bug Fix
- [ ] Feature
- [ ] Plugin

## Are all requirements met?

- [ ] Code completed
- [ ] Smoke tested
- [ ] Unit tests added
- [ ] Code documentation added
- [ ] Any pending items have an associated Issue

## Complete description
_How did you fix the bug, make the feature etc. Link to any design docs etc_

## Tracking Issue
https://github.com/flyteorg/flyte/issues/<number>

## Follow-up issue
_NA_
OR
_https://github.com/flyteorg/flyte/issues/<number>_

### CODE REVIEW

**Review by ByronHsu — APPROVED** [review]

**Comment by pingsutw** [comment]
@goyalankit could you run `make generate` to generate the new docs?

**Comment by goyalankit** [comment]
Running `make generate` doesn't produce any new file.

I tried running cd docs/ && make gendocs (with requirements installed). I get a pretty huge diff and not sure if there's a simpler way.

**Comment by pingsutw** [comment]
That's because we haven't updated the doc for a while. I think that's fine, you could push all of them.
cc @pmahindrakar-oss @evalsocket

**Review by pingsutw — APPROVED** [review]
Thank you @goyalankit

**Pull request merged**
