### PR TITLE
Add extra host to start command

### PR DESCRIPTION
**Pull request by pingsutw**
Signed-off-by: Kevin Su <pingsutw@apache.org>

# TL;DR
[slack thread](https://flyte-org.slack.com/archives/CP2HDHKE1/p1667231330440659)
Related to https://github.com/spotify/docker-client/issues/995
Failed to connect to webhook in the demo on ubuntu because k8s can't resolve the host name `host.docker.internal`.

## Type
- [x] Bug Fix
- [ ] Feature
- [ ] Plugin

## Are all requirements met?

- [x] Code completed
- [x] Smoke tested
- [ ] Unit tests added
- [ ] Code documentation added
- [ ] Any pending items have an associated Issue

## Complete description
^^^
## Tracking Issue
NA
## Follow-up issue
_NA_

### CODE REVIEW

**Review by hamersaw — CHANGES_REQUESTED** [review]
Can we set the `ExtraHosts` as a global variable [here](https://github.com/flyteorg/flytectl/blob/f454c31697312780a3edcb36d39d5b374deb415b/pkg/docker/docker_util.go#L26-L50)? This seems to be more aligned with the rest of the repo. Then it can be used in the tests similar to how `Environment` and `Volumes` are used as variables rather than explicitly setting the value.

**Comment by pingsutw** [comment]
make sense, updated it

**Comment by wild-endeavor** [comment]
unit test?

**Review by wild-endeavor — APPROVED** [review]
but unit test failing?

**Review by hamersaw — APPROVED** [review]

**Pull request merged**
